[package]
authors = ["Without Boats <woboats@gmail.com>"]
license = "AGPL-3.0+"
name = "notty"
version = "0.1.0"
workspace = "./scaffolding"

[dependencies]
base64 = "0.1.1"
mime = "0.1.3"
unicode-width = "0.1.3"

[dependencies.notty-encoding]
git = "https://github.com/withoutboats/notty-encoding"
